### ISSUE TITLE
About "Use_maintenance_window"

### ISSUE THREAD

**Issue by ghost** [MitchellGulledge/Meraki-vWAN#34]
When "Use_ maintenance_window" is set to "Yes", the following log is displayed in Azure and VPN is not created.
Setting "Use_ maintenance_window" to "No" creates a VPN.
What does "Use_ maintenance_window" mean?

Azure Log (Invocation Details):
Maintenance mode detected but it is not during scheduled hours or the vwan-apply-now tag has not been detected. Skipping updates

![](https://user-images.githubusercontent.com/61255163/122648451-3aa2d880-d0de-11eb-80ad-20b5102914e7.png)

**Comment by MitchellGulledge** [comment]
Maintenance mode detected but it is not during scheduled hours or the vwan-apply-now tag has not been detected. Skipping updates

This is essentially stating that we will not do a PUT to update the Meraki VPN config outside the specified maintenance time you specified. (This is due to the fact we may not want to make config changes during production hours to the site to site config) The way we can override that is by applying the vwan-apply-now tag to a Meraki network on the organization -> overview page on a selected network.

**Comment by ghost** [comment]
Issue Resolved
